# -*- coding: utf-8 -*-

# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/expr/v1beta1/value.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="google/api/expr/v1beta1/value.proto",
    package="google.api.expr.v1beta1",
    syntax="proto3",
    serialized_options=b"\n\033com.google.api.expr.v1beta1B\nValueProtoP\001Z;google.golang.org/genproto/googleapis/api/expr/v1beta1;expr\370\001\001",
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n#google/api/expr/v1beta1/value.proto\x12\x17google.api.expr.v1beta1\x1a\x19google/protobuf/any.proto\x1a\x1cgoogle/protobuf/struct.proto"\xbd\x03\n\x05Value\x12\x30\n\nnull_value\x18\x01 \x01(\x0e\x32\x1a.google.protobuf.NullValueH\x00\x12\x14\n\nbool_value\x18\x02 \x01(\x08H\x00\x12\x15\n\x0bint64_value\x18\x03 \x01(\x03H\x00\x12\x16\n\x0cuint64_value\x18\x04 \x01(\x04H\x00\x12\x16\n\x0c\x64ouble_value\x18\x05 \x01(\x01H\x00\x12\x16\n\x0cstring_value\x18\x06 \x01(\tH\x00\x12\x15\n\x0b\x62ytes_value\x18\x07 \x01(\x0cH\x00\x12\x38\n\nenum_value\x18\t \x01(\x0b\x32".google.api.expr.v1beta1.EnumValueH\x00\x12,\n\x0cobject_value\x18\n \x01(\x0b\x32\x14.google.protobuf.AnyH\x00\x12\x36\n\tmap_value\x18\x0b \x01(\x0b\x32!.google.api.expr.v1beta1.MapValueH\x00\x12\x38\n\nlist_value\x18\x0c \x01(\x0b\x32".google.api.expr.v1beta1.ListValueH\x00\x12\x14\n\ntype_value\x18\x0f \x01(\tH\x00\x42\x06\n\x04kind"(\n\tEnumValue\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05";\n\tListValue\x12.\n\x06values\x18\x01 \x03(\x0b\x32\x1e.google.api.expr.v1beta1.Value"\xa9\x01\n\x08MapValue\x12\x38\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\'.google.api.expr.v1beta1.MapValue.Entry\x1a\x63\n\x05\x45ntry\x12+\n\x03key\x18\x01 \x01(\x0b\x32\x1e.google.api.expr.v1beta1.Value\x12-\n\x05value\x18\x02 \x01(\x0b\x32\x1e.google.api.expr.v1beta1.ValueBk\n\x1b\x63om.google.api.expr.v1beta1B\nValueProtoP\x01Z;google.golang.org/genproto/googleapis/api/expr/v1beta1;expr\xf8\x01\x01\x62\x06proto3',
    dependencies=[
        google_dot_protobuf_dot_any__pb2.DESCRIPTOR,
        google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,
    ],
)


_VALUE = _descriptor.Descriptor(
    name="Value",
    full_name="google.api.expr.v1beta1.Value",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="null_value",
            full_name="google.api.expr.v1beta1.Value.null_value",
            index=0,
            number=1,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="bool_value",
            full_name="google.api.expr.v1beta1.Value.bool_value",
            index=1,
            number=2,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="int64_value",
            full_name="google.api.expr.v1beta1.Value.int64_value",
            index=2,
            number=3,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="uint64_value",
            full_name="google.api.expr.v1beta1.Value.uint64_value",
            index=3,
            number=4,
            type=4,
            cpp_type=4,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="double_value",
            full_name="google.api.expr.v1beta1.Value.double_value",
            index=4,
            number=5,
            type=1,
            cpp_type=5,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="string_value",
            full_name="google.api.expr.v1beta1.Value.string_value",
            index=5,
            number=6,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="bytes_value",
            full_name="google.api.expr.v1beta1.Value.bytes_value",
            index=6,
            number=7,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="enum_value",
            full_name="google.api.expr.v1beta1.Value.enum_value",
            index=7,
            number=9,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="object_value",
            full_name="google.api.expr.v1beta1.Value.object_value",
            index=8,
            number=10,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="map_value",
            full_name="google.api.expr.v1beta1.Value.map_value",
            index=9,
            number=11,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="list_value",
            full_name="google.api.expr.v1beta1.Value.list_value",
            index=10,
            number=12,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="type_value",
            full_name="google.api.expr.v1beta1.Value.type_value",
            index=11,
            number=15,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="kind",
            full_name="google.api.expr.v1beta1.Value.kind",
            index=0,
            containing_type=None,
            create_key=_descriptor._internal_create_key,
            fields=[],
        )
    ],
    serialized_start=122,
    serialized_end=567,
)


_ENUMVALUE = _descriptor.Descriptor(
    name="EnumValue",
    full_name="google.api.expr.v1beta1.EnumValue",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="type",
            full_name="google.api.expr.v1beta1.EnumValue.type",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="value",
            full_name="google.api.expr.v1beta1.EnumValue.value",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=569,
    serialized_end=609,
)


_LISTVALUE = _descriptor.Descriptor(
    name="ListValue",
    full_name="google.api.expr.v1beta1.ListValue",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="values",
            full_name="google.api.expr.v1beta1.ListValue.values",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        )
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=611,
    serialized_end=670,
)


_MAPVALUE_ENTRY = _descriptor.Descriptor(
    name="Entry",
    full_name="google.api.expr.v1beta1.MapValue.Entry",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="key",
            full_name="google.api.expr.v1beta1.MapValue.Entry.key",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="value",
            full_name="google.api.expr.v1beta1.MapValue.Entry.value",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=743,
    serialized_end=842,
)

_MAPVALUE = _descriptor.Descriptor(
    name="MapValue",
    full_name="google.api.expr.v1beta1.MapValue",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="entries",
            full_name="google.api.expr.v1beta1.MapValue.entries",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        )
    ],
    extensions=[],
    nested_types=[_MAPVALUE_ENTRY],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=673,
    serialized_end=842,
)

_VALUE.fields_by_name[
    "null_value"
].enum_type = google_dot_protobuf_dot_struct__pb2._NULLVALUE
_VALUE.fields_by_name["enum_value"].message_type = _ENUMVALUE
_VALUE.fields_by_name[
    "object_value"
].message_type = google_dot_protobuf_dot_any__pb2._ANY
_VALUE.fields_by_name["map_value"].message_type = _MAPVALUE
_VALUE.fields_by_name["list_value"].message_type = _LISTVALUE
_VALUE.oneofs_by_name["kind"].fields.append(_VALUE.fields_by_name["null_value"])
_VALUE.fields_by_name["null_value"].containing_oneof = _VALUE.oneofs_by_name["kind"]
_VALUE.oneofs_by_name["kind"].fields.append(_VALUE.fields_by_name["bool_value"])
_VALUE.fields_by_name["bool_value"].containing_oneof = _VALUE.oneofs_by_name["kind"]
_VALUE.oneofs_by_name["kind"].fields.append(_VALUE.fields_by_name["int64_value"])
_VALUE.fields_by_name["int64_value"].containing_oneof = _VALUE.oneofs_by_name["kind"]
_VALUE.oneofs_by_name["kind"].fields.append(_VALUE.fields_by_name["uint64_value"])
_VALUE.fields_by_name["uint64_value"].containing_oneof = _VALUE.oneofs_by_name["kind"]
_VALUE.oneofs_by_name["kind"].fields.append(_VALUE.fields_by_name["double_value"])
_VALUE.fields_by_name["double_value"].containing_oneof = _VALUE.oneofs_by_name["kind"]
_VALUE.oneofs_by_name["kind"].fields.append(_VALUE.fields_by_name["string_value"])
_VALUE.fields_by_name["string_value"].containing_oneof = _VALUE.oneofs_by_name["kind"]
_VALUE.oneofs_by_name["kind"].fields.append(_VALUE.fields_by_name["bytes_value"])
_VALUE.fields_by_name["bytes_value"].containing_oneof = _VALUE.oneofs_by_name["kind"]
_VALUE.oneofs_by_name["kind"].fields.append(_VALUE.fields_by_name["enum_value"])
_VALUE.fields_by_name["enum_value"].containing_oneof = _VALUE.oneofs_by_name["kind"]
_VALUE.oneofs_by_name["kind"].fields.append(_VALUE.fields_by_name["object_value"])
_VALUE.fields_by_name["object_value"].containing_oneof = _VALUE.oneofs_by_name["kind"]
_VALUE.oneofs_by_name["kind"].fields.append(_VALUE.fields_by_name["map_value"])
_VALUE.fields_by_name["map_value"].containing_oneof = _VALUE.oneofs_by_name["kind"]
_VALUE.oneofs_by_name["kind"].fields.append(_VALUE.fields_by_name["list_value"])
_VALUE.fields_by_name["list_value"].containing_oneof = _VALUE.oneofs_by_name["kind"]
_VALUE.oneofs_by_name["kind"].fields.append(_VALUE.fields_by_name["type_value"])
_VALUE.fields_by_name["type_value"].containing_oneof = _VALUE.oneofs_by_name["kind"]
_LISTVALUE.fields_by_name["values"].message_type = _VALUE
_MAPVALUE_ENTRY.fields_by_name["key"].message_type = _VALUE
_MAPVALUE_ENTRY.fields_by_name["value"].message_type = _VALUE
_MAPVALUE_ENTRY.containing_type = _MAPVALUE
_MAPVALUE.fields_by_name["entries"].message_type = _MAPVALUE_ENTRY
DESCRIPTOR.message_types_by_name["Value"] = _VALUE
DESCRIPTOR.message_types_by_name["EnumValue"] = _ENUMVALUE
DESCRIPTOR.message_types_by_name["ListValue"] = _LISTVALUE
DESCRIPTOR.message_types_by_name["MapValue"] = _MAPVALUE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Value = _reflection.GeneratedProtocolMessageType(
    "Value",
    (_message.Message,),
    {
        "DESCRIPTOR": _VALUE,
        "__module__": "google.api.expr.v1beta1.value_pb2"
        # @@protoc_insertion_point(class_scope:google.api.expr.v1beta1.Value)
    },
)
_sym_db.RegisterMessage(Value)

EnumValue = _reflection.GeneratedProtocolMessageType(
    "EnumValue",
    (_message.Message,),
    {
        "DESCRIPTOR": _ENUMVALUE,
        "__module__": "google.api.expr.v1beta1.value_pb2"
        # @@protoc_insertion_point(class_scope:google.api.expr.v1beta1.EnumValue)
    },
)
_sym_db.RegisterMessage(EnumValue)

ListValue = _reflection.GeneratedProtocolMessageType(
    "ListValue",
    (_message.Message,),
    {
        "DESCRIPTOR": _LISTVALUE,
        "__module__": "google.api.expr.v1beta1.value_pb2"
        # @@protoc_insertion_point(class_scope:google.api.expr.v1beta1.ListValue)
    },
)
_sym_db.RegisterMessage(ListValue)

MapValue = _reflection.GeneratedProtocolMessageType(
    "MapValue",
    (_message.Message,),
    {
        "Entry": _reflection.GeneratedProtocolMessageType(
            "Entry",
            (_message.Message,),
            {
                "DESCRIPTOR": _MAPVALUE_ENTRY,
                "__module__": "google.api.expr.v1beta1.value_pb2"
                # @@protoc_insertion_point(class_scope:google.api.expr.v1beta1.MapValue.Entry)
            },
        ),
        "DESCRIPTOR": _MAPVALUE,
        "__module__": "google.api.expr.v1beta1.value_pb2"
        # @@protoc_insertion_point(class_scope:google.api.expr.v1beta1.MapValue)
    },
)
_sym_db.RegisterMessage(MapValue)
_sym_db.RegisterMessage(MapValue.Entry)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
