# -*- coding: utf-8 -*-

# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/api/expr/v1alpha1/explain.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api.expr.v1alpha1 import (
    value_pb2 as google_dot_api_dot_expr_dot_v1alpha1_dot_value__pb2,
)


DESCRIPTOR = _descriptor.FileDescriptor(
    name="google/api/expr/v1alpha1/explain.proto",
    package="google.api.expr.v1alpha1",
    syntax="proto3",
    serialized_options=b"\n\034com.google.api.expr.v1alpha1B\014ExplainProtoP\001Z<google.golang.org/genproto/googleapis/api/expr/v1alpha1;expr\370\001\001",
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n&google/api/expr/v1alpha1/explain.proto\x12\x18google.api.expr.v1alpha1\x1a$google/api/expr/v1alpha1/value.proto"\xab\x01\n\x07\x45xplain\x12/\n\x06values\x18\x01 \x03(\x0b\x32\x1f.google.api.expr.v1alpha1.Value\x12>\n\nexpr_steps\x18\x02 \x03(\x0b\x32*.google.api.expr.v1alpha1.Explain.ExprStep\x1a+\n\x08\x45xprStep\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x13\n\x0bvalue_index\x18\x02 \x01(\x05:\x02\x18\x01\x42o\n\x1c\x63om.google.api.expr.v1alpha1B\x0c\x45xplainProtoP\x01Z<google.golang.org/genproto/googleapis/api/expr/v1alpha1;expr\xf8\x01\x01\x62\x06proto3',
    dependencies=[google_dot_api_dot_expr_dot_v1alpha1_dot_value__pb2.DESCRIPTOR],
)


_EXPLAIN_EXPRSTEP = _descriptor.Descriptor(
    name="ExprStep",
    full_name="google.api.expr.v1alpha1.Explain.ExprStep",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="google.api.expr.v1alpha1.Explain.ExprStep.id",
            index=0,
            number=1,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="value_index",
            full_name="google.api.expr.v1alpha1.Explain.ExprStep.value_index",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=231,
    serialized_end=274,
)

_EXPLAIN = _descriptor.Descriptor(
    name="Explain",
    full_name="google.api.expr.v1alpha1.Explain",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="values",
            full_name="google.api.expr.v1alpha1.Explain.values",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="expr_steps",
            full_name="google.api.expr.v1alpha1.Explain.expr_steps",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[_EXPLAIN_EXPRSTEP],
    enum_types=[],
    serialized_options=b"\030\001",
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=107,
    serialized_end=278,
)

_EXPLAIN_EXPRSTEP.containing_type = _EXPLAIN
_EXPLAIN.fields_by_name[
    "values"
].message_type = google_dot_api_dot_expr_dot_v1alpha1_dot_value__pb2._VALUE
_EXPLAIN.fields_by_name["expr_steps"].message_type = _EXPLAIN_EXPRSTEP
DESCRIPTOR.message_types_by_name["Explain"] = _EXPLAIN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Explain = _reflection.GeneratedProtocolMessageType(
    "Explain",
    (_message.Message,),
    {
        "ExprStep": _reflection.GeneratedProtocolMessageType(
            "ExprStep",
            (_message.Message,),
            {
                "DESCRIPTOR": _EXPLAIN_EXPRSTEP,
                "__module__": "google.api.expr.v1alpha1.explain_pb2"
                # @@protoc_insertion_point(class_scope:google.api.expr.v1alpha1.Explain.ExprStep)
            },
        ),
        "DESCRIPTOR": _EXPLAIN,
        "__module__": "google.api.expr.v1alpha1.explain_pb2"
        # @@protoc_insertion_point(class_scope:google.api.expr.v1alpha1.Explain)
    },
)
_sym_db.RegisterMessage(Explain)
_sym_db.RegisterMessage(Explain.ExprStep)


DESCRIPTOR._options = None
_EXPLAIN._options = None
# @@protoc_insertion_point(module_scope)
